<a href="https://colab.research.google.com/github/PrantoMondol11/Machine-learning-/blob/main/Fashion_MINST.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.
import kagglehub
zalando_research_fashionmnist_path = kagglehub.dataset_download('zalando-research/fashionmnist')

print('Data source import complete.')

In [ ]:
import pandas as pd

In [ ]:
import os

# List everything in the input directory
print(os.listdir('/kaggle/input'))

# Walk through all subdirectories and files
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

['datasets']
/kaggle/input/datasets/organizations/zalando-research/fashionmnist/t10k-labels-idx1-ubyte
/kaggle/input/datasets/organizations/zalando-research/fashionmnist/t10k-images-idx3-ubyte
/kaggle/input/datasets/organizations/zalando-research/fashionmnist/fashion-mnist_test.csv
/kaggle/input/datasets/organizations/zalando-research/fashionmnist/fashion-mnist_train.csv
/kaggle/input/datasets/organizations/zalando-research/fashionmnist/train-labels-idx1-ubyte
/kaggle/input/datasets/organizations/zalando-research/fashionmnist/train-images-idx3-ubyte

In [ ]:
df=pd.read_csv("/kaggle/input/datasets/organizations/zalando-research/fashionmnist/fashion-mnist_train.csv")

In [ ]:
df2=pd.read_csv("/kaggle/input/datasets/organizations/zalando-research/fashionmnist/fashion-mnist_test.csv")

In [ ]:
import torch

device=torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"using gpu: {device}")

using gpu: cuda

In [ ]:
df2.head()

,label,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
0,0,0,0,0,0,0,0,0,9,8,...,103,87,56,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,34,0,0,0,0,0,0,0,0,0
2,2,0,0,0,0,0,0,14,53,99,...,0,0,0,0,63,53,31,0,0,0
3,2,0,0,0,0,0,0,0,0,0,...,137,126,140,0,133,224,222,56,0,0
4,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
X_test=df2.iloc[:,1:]
y_test=df2.iloc[:,0]

In [ ]:

import numpy as np
X_test=np.array(X_test)
X_test_tensor=torch.tensor(X_test)
y_test=np.array(y_test)
y_test_tensor=torch.tensor(y_test)

In [ ]:
df.head()

,label,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
0,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,6,0,0,0,0,0,0,0,5,0,...,0,0,0,30,43,0,0,0,0,0
3,0,0,0,0,1,2,0,0,0,0,...,3,0,0,0,0,1,0,0,0,0
4,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
df.shape
import numpy as np

In [ ]:
df1=df

In [ ]:
df1.shape

(60000, 785)

In [ ]:
df1.head()

,label,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
0,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,6,0,0,0,0,0,0,0,5,0,...,0,0,0,30,43,0,0,0,0,0
3,0,0,0,0,1,2,0,0,0,0,...,3,0,0,0,0,1,0,0,0,0
4,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
X_train=df1.iloc[:,1:]

In [ ]:
y_train=df1.iloc[:,0]

In [ ]:
X_train.shape

(60000, 784)

In [ ]:
import torch
X_train=np.array(X_train)
X_train_tensor=torch.tensor(X_train)
y_train=np.array(y_train)
y_train_tensor=torch.tensor(y_train)

In [ ]:
X_train_tensor=X_train_tensor/255.00
X_test_tensor=X_test_tensor/255.00

In [ ]:
X_train_tensor

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [ ]:
from torch.utils.data import Dataset,DataLoader
class CustomDataset(Dataset):
    def __init__(self,features,label):
        self.features=features
        self.label=label
    def __len__(self):
        return len(self.features)

    def __getitem__(self,idx):
        x=self.features[idx]
        y=self.label[idx]
        return x,y

In [ ]:
dataset=CustomDataset(X_train_tensor,y_train_tensor)
dataset2=CustomDataset(X_test_tensor,y_test_tensor)
train_loader=DataLoader(dataset2,batch_size=32,shuffle=False,pin_memory=True)
dataloader=DataLoader(dataset,batch_size=32,shuffle=True,pin_memory=True)

In [ ]:
import torch.nn as nn

In [ ]:
class Model1(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        self.model=nn.Sequential(
            nn.Linear(num_features,128),
            nn.ReLU(),
            nn.Linear(128,64),
            nn.ReLU(),
            nn.Linear(64,10)
        )
    def forward(self,x):
        return self.model(x)

In [ ]:
loss1=nn.CrossEntropyLoss()
model=Model1(X_train_tensor.shape[1])
model=model.to(device)

In [ ]:
optimizer=torch.optim.SGD(model.parameters(),lr=0.01)

In [ ]:
epochs=100

In [ ]:
for epoch in range(epochs):
    total_epoch_loss=0
    for batch_features,batch_labels in dataloader:
        batch_features,batch_labels=batch_features.to(device),batch_labels.to(device)
        output= model(batch_features)
        loss=loss1(output,batch_labels)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        total_epoch_loss+=loss.item()

    avg_loss=total_epoch_loss/len(dataloader)
    print(f"Epoch: {epoch+1} , Avg Loss {avg_loss}")

Epoch: 1 , Avg Loss 1.109228040154775
Epoch: 2 , Avg Loss 0.598900456905365
Epoch: 3 , Avg Loss 0.5135716037511826
Epoch: 4 , Avg Loss 0.4758406643390656
Epoch: 5 , Avg Loss 0.4519305268764496
Epoch: 6 , Avg Loss 0.4331111429929733
Epoch: 7 , Avg Loss 0.4173641365408897
Epoch: 8 , Avg Loss 0.4032388570904732
Epoch: 9 , Avg Loss 0.3913564660072327
Epoch: 10 , Avg Loss 0.3796333002408346
Epoch: 11 , Avg Loss 0.3703928504784902
Epoch: 12 , Avg Loss 0.3615628113706907
Epoch: 13 , Avg Loss 0.35294560922781626
Epoch: 14 , Avg Loss 0.3459995371381442
Epoch: 15 , Avg Loss 0.33868104459047316
Epoch: 16 , Avg Loss 0.3314674943844477
Epoch: 17 , Avg Loss 0.3257170408566793
Epoch: 18 , Avg Loss 0.3197680607060591
Epoch: 19 , Avg Loss 0.3136214117626349
Epoch: 20 , Avg Loss 0.3092049842039744
Epoch: 21 , Avg Loss 0.3037849497616291
Epoch: 22 , Avg Loss 0.2989002371668816
Epoch: 23 , Avg Loss 0.2947714968383312
Epoch: 24 , Avg Loss 0.28968308765292167
Epoch: 25 , Avg Loss 0.2857025211751461
Epoch: 26 , Avg Loss 0.2814645171662172
Epoch: 27 , Avg Loss 0.27783327890634535
Epoch: 28 , Avg Loss 0.27348724312583605
Epoch: 29 , Avg Loss 0.2705901198943456
Epoch: 30 , Avg Loss 0.2663774044831594
Epoch: 31 , Avg Loss 0.2625752700388432
Epoch: 32 , Avg Loss 0.2597594855343302
Epoch: 33 , Avg Loss 0.2567144335846106
Epoch: 34 , Avg Loss 0.2527869473516941
Epoch: 35 , Avg Loss 0.24974377391338348
Epoch: 36 , Avg Loss 0.24615445731282234
Epoch: 37 , Avg Loss 0.24307217134137948
Epoch: 38 , Avg Loss 0.24067971641818683
Epoch: 39 , Avg Loss 0.2376118668973446
Epoch: 40 , Avg Loss 0.23450585526227952

In [ ]:
model.eval()

In [ ]:
total=0
correct=0

with torch.no_grad():
    for batch_features,batch_labels in train_loader:
        batch_features,batch_labels=batch_features.to(device),batch_labels.to(device)
        outputs=model(batch_features)
        _,predictes=torch.max(outputs,1)
        total+=batch_labels.shape[0]
        correct+=(predictes==batch_labels).sum().item()
print(correct/total)

In [ ]:
print(total)