<a href="https://colab.research.google.com/github/PrantoMondol11/Machine-learning-/blob/main/Fashion_MINST.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.
import kagglehub
zalando_research_fashionmnist_path = kagglehub.dataset_download('zalando-research/fashionmnist')

print('Data source import complete.')

In [ ]:
import pandas as pd

In [ ]:
import os

# List everything in the input directory
print(os.listdir('/kaggle/input'))

# Walk through all subdirectories and files
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

['datasets']
/kaggle/input/datasets/organizations/zalando-research/fashionmnist/t10k-labels-idx1-ubyte
/kaggle/input/datasets/organizations/zalando-research/fashionmnist/t10k-images-idx3-ubyte
/kaggle/input/datasets/organizations/zalando-research/fashionmnist/fashion-mnist_test.csv
/kaggle/input/datasets/organizations/zalando-research/fashionmnist/fashion-mnist_train.csv
/kaggle/input/datasets/organizations/zalando-research/fashionmnist/train-labels-idx1-ubyte
/kaggle/input/datasets/organizations/zalando-research/fashionmnist/train-images-idx3-ubyte

In [ ]:
df=pd.read_csv("/kaggle/input/datasets/organizations/zalando-research/fashionmnist/fashion-mnist_train.csv")

In [ ]:
df2=pd.read_csv("/kaggle/input/datasets/organizations/zalando-research/fashionmnist/fashion-mnist_test.csv")

In [ ]:
import torch

device=torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"using gpu: {device}")

using gpu: cuda

In [ ]:
df2.head()

,label,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
0,0,0,0,0,0,0,0,0,9,8,...,103,87,56,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,34,0,0,0,0,0,0,0,0,0
2,2,0,0,0,0,0,0,14,53,99,...,0,0,0,0,63,53,31,0,0,0
3,2,0,0,0,0,0,0,0,0,0,...,137,126,140,0,133,224,222,56,0,0
4,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
X_test=df2.iloc[:,1:]
y_test=df2.iloc[:,0]

In [ ]:

import numpy as np
X_test=np.array(X_test)
X_test_tensor=torch.tensor(X_test)
y_test=np.array(y_test)
y_test_tensor=torch.tensor(y_test)

In [ ]:
df.head()

,label,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
0,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,6,0,0,0,0,0,0,0,5,0,...,0,0,0,30,43,0,0,0,0,0
3,0,0,0,0,1,2,0,0,0,0,...,3,0,0,0,0,1,0,0,0,0
4,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
df.shape
import numpy as np

In [ ]:
df1=df

In [ ]:
df1.shape

(60000, 785)

In [ ]:
df1.head()

,label,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
0,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,6,0,0,0,0,0,0,0,5,0,...,0,0,0,30,43,0,0,0,0,0
3,0,0,0,0,1,2,0,0,0,0,...,3,0,0,0,0,1,0,0,0,0
4,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
X_train=df1.iloc[:,1:]

In [ ]:
y_train=df1.iloc[:,0]

In [ ]:
X_train.shape

(60000, 784)

In [ ]:
import torch
X_train=np.array(X_train)
X_train_tensor=torch.tensor(X_train)
y_train=np.array(y_train)
y_train_tensor=torch.tensor(y_train)

In [ ]:
X_train_tensor=X_train_tensor/255.00
X_test_tensor=X_test_tensor/255.00

In [ ]:
X_train_tensor

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [ ]:
from torch.utils.data import Dataset,DataLoader
class CustomDataset(Dataset):
    def __init__(self,features,label):
        self.features=features
        self.label=label
    def __len__(self):
        return len(self.features)

    def __getitem__(self,idx):
        x=self.features[idx]
        y=self.label[idx]
        return x,y

In [ ]:
dataset=CustomDataset(X_train_tensor,y_train_tensor)
dataset2=CustomDataset(X_test_tensor,y_test_tensor)

In [ ]:
import torch.nn as nn

In [ ]:
class Model1(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        self.model=nn.Sequential(
            nn.Linear(num_features,128),
            nn.BatchNorm1d(128),
            nn.ReLU(),
            nn.Dropout(p=0.3),
            nn.Linear(128,64),
            nn.BatchNorm1d(64),
            nn.ReLU(),
            nn.Dropout(p=0.3 ),
            nn.Linear(64,10)
        )
    def forward(self,x):
        return self.model(x)

In [ ]:
loss1=nn.CrossEntropyLoss()
model=Model1(X_train_tensor.shape[1])
model=model.to(device)

In [ ]:
optimizer=torch.optim.SGD(model.parameters(),lr=0.01,weight_decay=1e-4)

In [ ]:
epochs=100

In [ ]:
def objective(trail):

    num_hidden_layers=trail.suggest_int("num_hidden_layers",1,5)
    neurons_per_layer=trail.suggest_int("neurons_per_layer",8,128,step=8)
    learning_rate=trail.suggest_float("learning_rate",1e-4,1e-1,log=True)
    epochs=trail.suggest_int("epochs",10,50,step=10)
    dropout_rate=trail.dropout("dropout_rate",0.1,1,step=.1)
    batch_size=trail.suggest_catagorical("batch_size",[16,32,64,128])
    optimizer_name=trail.suggest_catagorical("optimizer",["Adam","SGD","RMSprop"])
    weight_decay=train.suggest_float("weight_decay",1e-5,1e-3,log=True)
    train_loader=DataLoader(dataset2,batch_size=batch_size,shuffle=False,pin_memory=True)
    dataloader=DataLoader(dataset,batch_size=batch_size,shuffle=True,pin_memory=True)

    input_dim=784
    output_dim=10

    model=MyNN(input_dim,output_dim,num_hidden_layers,neurons_per_layer,dropout_rate)
    model.to(device)



    criterion=nn.CrossEntropyLoss()

    if optimizer_name=="SGD":
       optimizer=torch.optim.SGD(model.parameters(),lr=learning_rate,weight_decay=weight_decay)
    elif optimizer_name=="Adam":
        optimizer=torch.optim.Adam(model.parameters(),lr=learning_rate,weight_decay=weight_decay)
    else:
        optimizer=torch.optim.RSEprop(model.parameters(),lr=learning_rate,weight_decay=weight_decay)


    for epoch in range(epochs):
        for batch_features,batch_labels in dataloader:
            batch_features,batch_labels=batch_features.to(device),batch_labels.to(device)
            output= model(batch_features)
            loss=loss1(output,batch_labels)
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

    total=0
    correct=0

    with torch.no_grad():
        for batch_features,batch_labels in train_loader:
            batch_features,batch_labels=batch_features.to(device),batch_labels.to(device)
            outputs=model(batch_features)
            _,predictes=torch.max(outputs,1)
            total+=batch_labels.shape[0]
            correct+=(predictes==batch_labels).sum().item()
    accuracy=(correct/total)



    return accuracy

In [ ]:
class MyNN(nn.Module):
    def __init__(self,input_dim,output_dim,num_hidden_layers,neurons_per_layer,learning_rate,dropout_rate):
        super().__init__()

        layers=[]

        for i in range(num_hidden_layers):
            layers.append(nn.Linear(input_dim,neurons_per_layer))
            layers.append(nn.BatchNorm1d(neurons_per_layer))
            layers.append(nn.ReLU())
            layers.append(nn.Dropout(dropout_rate))
            input_dim=neurons_per_layer

        layers.append(nn.Linear(input_dim,output_dim))

        self.model=nn.Sequential(*layers)
    def forward(self,x):
        return self.model(x)

In [ ]:
for epoch in range(epochs):
    total_epoch_loss=0
    for batch_features,batch_labels in dataloader:
        batch_features,batch_labels=batch_features.to(device),batch_labels.to(device)
        output= model(batch_features)
        loss=loss1(output,batch_labels)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        total_epoch_loss+=loss.item()

    avg_loss=total_epoch_loss/len(dataloader)
    print(f"Epoch: {epoch+1} , Avg Loss {avg_loss}")

Epoch: 1 , Avg Loss 0.7716672263940175
Epoch: 2 , Avg Loss 0.5448117675463359
Epoch: 3 , Avg Loss 0.4951176311095556
Epoch: 4 , Avg Loss 0.46927588344812393
Epoch: 5 , Avg Loss 0.45056542261044186
Epoch: 6 , Avg Loss 0.43876036074558894
Epoch: 7 , Avg Loss 0.4209505473256111
Epoch: 8 , Avg Loss 0.4085408970872561
Epoch: 9 , Avg Loss 0.4022418893059095
Epoch: 10 , Avg Loss 0.39538706222772596
Epoch: 11 , Avg Loss 0.38551582868496576
Epoch: 12 , Avg Loss 0.38226483842929204
Epoch: 13 , Avg Loss 0.3739600906630357
Epoch: 14 , Avg Loss 0.3714648327112198
Epoch: 15 , Avg Loss 0.3651808053294818
Epoch: 16 , Avg Loss 0.35546378613710405
Epoch: 17 , Avg Loss 0.3560494712511698
Epoch: 18 , Avg Loss 0.35152215626041095
Epoch: 19 , Avg Loss 0.3470506493429343
Epoch: 20 , Avg Loss 0.34105035456021626
Epoch: 21 , Avg Loss 0.3388200332601865
Epoch: 22 , Avg Loss 0.3367554755687714
Epoch: 23 , Avg Loss 0.33379738366007805
Epoch: 24 , Avg Loss 0.32948752206563947
Epoch: 25 , Avg Loss 0.328968243487676
Epoch: 26 , Avg Loss 0.32393323047359784
Epoch: 27 , Avg Loss 0.3245869676152865
Epoch: 28 , Avg Loss 0.31815080599188805
Epoch: 29 , Avg Loss 0.31718827618757883
Epoch: 30 , Avg Loss 0.315824489514033
Epoch: 31 , Avg Loss 0.31024415624936424
Epoch: 32 , Avg Loss 0.30846168630719184
Epoch: 33 , Avg Loss 0.3055881939947605
Epoch: 34 , Avg Loss 0.30488732124765716
Epoch: 35 , Avg Loss 0.304805530299743
Epoch: 36 , Avg Loss 0.30045566466649376
Epoch: 37 , Avg Loss 0.29613269849618273
Epoch: 38 , Avg Loss 0.29729855832854907
Epoch: 39 , Avg Loss 0.29462547910610837
Epoch: 40 , Avg Loss 0.2911725441992283
Epoch: 41 , Avg Loss 0.2945260235329469
Epoch: 42 , Avg Loss 0.2909308737397194
Epoch: 43 , Avg Loss 0.28937166556517285
Epoch: 44 , Avg Loss 0.2872265145222346
Epoch: 45 , Avg Loss 0.2858019334336122
Epoch: 46 , Avg Loss 0.2857025829394658
Epoch: 47 , Avg Loss 0.2831792168329159
Epoch: 48 , Avg Loss 0.2821511660675208
Epoch: 49 , Avg Loss 0.2796245538532734
Epoch: 50 , Avg Loss 0.27824171617031096
Epoch: 51 , Avg Loss 0.276996195786198
Epoch: 52 , Avg Loss 0.280216845736901
Epoch: 53 , Avg Loss 0.2746402869462967
Epoch: 54 , Avg Loss 0.27369957347710927
Epoch: 55 , Avg Loss 0.27278387543360394
Epoch: 56 , Avg Loss 0.27018455572326977
Epoch: 57 , Avg Loss 0.27075606630245846
Epoch: 58 , Avg Loss 0.2665769609073798
Epoch: 59 , Avg Loss 0.2633534879823526
Epoch: 60 , Avg Loss 0.26605551321705184
Epoch: 61 , Avg Loss 0.2673420207222303
Epoch: 62 , Avg Loss 0.2668663988053799
Epoch: 63 , Avg Loss 0.2613574637929599
Epoch: 64 , Avg Loss 0.2600709971129894
Epoch: 65 , Avg Loss 0.2601434703171253
Epoch: 66 , Avg Loss 0.25894495001832646
Epoch: 67 , Avg Loss 0.2604736257294814
Epoch: 68 , Avg Loss 0.25730763211250307
Epoch: 69 , Avg Loss 0.25567979916532835
Epoch: 70 , Avg Loss 0.25779704331457615
Epoch: 71 , Avg Loss 0.2562841053525607
Epoch: 72 , Avg Loss 0.2519687994837761
Epoch: 73 , Avg Loss 0.25040954574743907
Epoch: 74 , Avg Loss 0.25202722941239675
Epoch: 75 , Avg Loss 0.24889880097905795
Epoch: 76 , Avg Loss 0.2548579069018364
Epoch: 77 , Avg Loss 0.24596911154588064
Epoch: 78 , Avg Loss 0.2508498389532169
Epoch: 79 , Avg Loss 0.25016146106123927
Epoch: 80 , Avg Loss 0.2470584044655164
Epoch: 81 , Avg Loss 0.2500985084513823
Epoch: 82 , Avg Loss 0.2471751007348299
Epoch: 83 , Avg Loss 0.246993162047863
Epoch: 84 , Avg Loss 0.2500820008158684
Epoch: 85 , Avg Loss 0.24727445333798725
Epoch: 86 , Avg Loss 0.24462123097578684
Epoch: 87 , Avg Loss 0.24446473107834657
Epoch: 88 , Avg Loss 0.23921842808425425
Epoch: 89 , Avg Loss 0.24050225741863251
Epoch: 90 , Avg Loss 0.2423864700516065
Epoch: 91 , Avg Loss 0.23963290556073188
Epoch: 92 , Avg Loss 0.24079021904369197
Epoch: 93 , Avg Loss 0.23856265931924184
Epoch: 94 , Avg Loss 0.23950001480380695
Epoch: 95 , Avg Loss 0.24217977269887925
Epoch: 96 , Avg Loss 0.23515197503169377
Epoch: 97 , Avg Loss 0.23453527975976468
Epoch: 98 , Avg Loss 0.2360792084356149
Epoch: 99 , Avg Loss 0.23799168964525064
Epoch: 100 , Avg Loss 0.24017192863126596

In [ ]:
model.eval()

Model1(
  (model): Sequential(
    (0): Linear(in_features=784, out_features=128, bias=True)
    (1): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): ReLU()
    (3): Dropout(p=0.3, inplace=False)
    (4): Linear(in_features=128, out_features=64, bias=True)
    (5): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (6): ReLU()
    (7): Dropout(p=0.3, inplace=False)
    (8): Linear(in_features=64, out_features=10, bias=True)
  )
)

In [ ]:
total=0
correct=0

with torch.no_grad():
    for batch_features,batch_labels in train_loader:
        batch_features,batch_labels=batch_features.to(device),batch_labels.to(device)
        outputs=model(batch_features)
        _,predictes=torch.max(outputs,1)
        total+=batch_labels.shape[0]
        correct+=(predictes==batch_labels).sum().item()
print(correct/total)

0.8999

In [ ]:
print(total)

In [ ]:
!pip install optuna

Requirement already satisfied: optuna in /usr/local/lib/python3.12/dist-packages (4.9.0)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (1.18.4)
Requirement already satisfied: colorlog in /usr/local/lib/python3.12/dist-packages (from optuna) (6.10.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (26.1)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.49)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (1.3.11)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.4.0)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna) (3.0.3)

In [ ]:
import optuna

In [ ]:
study=optuna.create_study(direction='maximize')

[I 2026-08-07 18:39:54,732] A new study created in memory with name: no-name-572f82a7-dd15-4cff-b323-f3cd486f26ba

In [ ]:
study.optimize(objective,n_trials=10)

[I 2026-08-07 18:56:58,741] Trial 4 finished with value: 0.3162 and parameters: {'num_hidden_layers': 5, 'neurons_per_layer': 8}. Best is trial 4 with value: 0.3162.
[I 2026-08-07 19:06:13,495] Trial 5 finished with value: 0.8679 and parameters: {'num_hidden_layers': 2, 'neurons_per_layer': 112}. Best is trial 5 with value: 0.8679.
[I 2026-08-07 19:20:02,734] Trial 6 finished with value: 0.8615 and parameters: {'num_hidden_layers': 5, 'neurons_per_layer': 120}. Best is trial 5 with value: 0.8679.
[I 2026-08-07 19:30:54,504] Trial 7 finished with value: 0.8524 and parameters: {'num_hidden_layers': 3, 'neurons_per_layer': 72}. Best is trial 5 with value: 0.8679.
[I 2026-08-07 19:38:44,348] Trial 8 finished with value: 0.8537 and parameters: {'num_hidden_layers': 1, 'neurons_per_layer': 56}. Best is trial 5 with value: 0.8679.
[I 2026-08-07 19:46:35,548] Trial 9 finished with value: 0.8679 and parameters: {'num_hidden_layers': 1, 'neurons_per_layer': 88}. Best is trial 5 with value: 0.8679.