<a href="https://colab.research.google.com/github/PrantoMondol11/Machine-learning-/blob/main/NN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [72]:
import torch.nn as nn
import torch

In [73]:
class Model(nn.Module):
  def __init__(self,num_features):
      super().__init__()
      self.linear=nn.Linear(num_features,1)
      self.sigmoid=nn.Sigmoid()
  def forward(self,features):
    out=self.linear(features)
    out=self.sigmoid(out)
    return out

In [74]:
features=torch.rand(10,5)

In [75]:
features

tensor([[0.3509, 0.3155, 0.3631, 0.5386, 0.5958],
        [0.5552, 0.7875, 0.8727, 0.1965, 0.4326],
        [0.7030, 0.2869, 0.5536, 0.5468, 0.1375],
        [0.5301, 0.1069, 0.9766, 0.9654, 0.4972],
        [0.1492, 0.1040, 0.1881, 0.3268, 0.4983],
        [0.8780, 0.1664, 0.7752, 0.5059, 0.5586],
        [0.8138, 0.9765, 0.7662, 0.0625, 0.6080],
        [0.2020, 0.8326, 0.7176, 0.1583, 0.3462],
        [0.6466, 0.4068, 0.7394, 0.2186, 0.3951],
        [0.7726, 0.7261, 0.6945, 0.3960, 0.7242]])

In [76]:
!pip install torchinfo

Requirement already satisfied: torchinfo in /usr/local/lib/python3.12/dist-packages (1.8.0)

In [77]:
import torch
import torch.nn as nn

class Model2(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.network=nn.Sequential(
        nn.Linear(num_features,1),
        nn.Sigmoid()
    )

  def forward(features):
    out=nn.network(features)
    return out

In [78]:
from os import read
import numpy as np
import pandas as pd

In [79]:
df=pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")

In [80]:
df.drop(columns=["id","Unnamed: 32"],inplace=True)

In [81]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [82]:
X_train=df.iloc[:,1:]
y_train=df.iloc[:,0]

In [83]:
y_train

0      M
1      M
2      M
3      M
4      M
      ..
564    M
565    M
566    M
567    M
568    B
Name: diagnosis, Length: 569, dtype: object

In [84]:
from sklearn.preprocessing  import  StandardScaler, LabelEncoder

In [85]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)

In [86]:
X_train_tensor=torch.from_numpy(X_train)
y_train_tensor=torch.from_numpy(y_train)
X_train_tensor = X_train_tensor.float()
y_train_tensor = y_train_tensor.float()

In [87]:
X_train_tensor.dtype

torch.float32

In [99]:
lr=0.1
epochs=30


import torch
import torch.nn as nn

class Model2(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.network=nn.Sequential(
        nn.Linear(num_features,1),
        nn.Sigmoid()
    )

  def forward(self,features):
    out=self.network(features)
    return out

In [100]:
model=Model2(X_train_tensor.shape[1])
loss_func=nn.BCELoss()
optimizer=torch.optim.SGD(model.parameters(),lr=lr,)

for epoch in range(epochs):
  optimizer.zero_grad()
  y_pred=model.forward(X_train_tensor)
  loss=loss_func(y_pred,y_train_tensor.view(-1,1))
  loss.backward()
  optimizer.step()

In [101]:
from sklearn.model_selection import train_test_split

In [102]:
X_train,X_test,y_train,y_test=train_test_split(X_train_tensor,y_train_tensor,test_size=0.2,random_state=42)

In [103]:
with torch.no_grad():
  y_pred=model.forward(X_test)
  y_pred=(y_pred>0.5).float()
  accuracy=(y_pred==y_test).float().mean()
  print(f"accuracy: {accuracy.item()}")

accuracy: 0.5301631093025208